#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

location=$YNH_APP_ARG_LOCATION

app=$YNH_APP_INSTANCE_NAME

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================


final_path=/etc/$app
test ! -e "$final_path" || ynh_die --message="This path already contains a folder"


#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression --message="Storing installation settings..." --time --weight=1

ynh_app_setting_set --app=$app --key=location --value=$location

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --time --weight=30

ynh_app_setting_set --app=$app --key=final_path --value=$final_path
# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$final_path"

chown -R root: $final_path

#=================================================
# SPECIFIC SETUP
#=================================================
# COPY ITEMS AND SET PERMISSIONS
#=================================================

mv "$final_path/moth/" "/usr/share/ssowat/portal/assets/themes/moth/"
ynh_script_progression --message="Copying source files..." --time --weight=15


mv "/etc/ssowat/conf.json.persistent" "/etc/ssowat/conf.json.persistent.old"
mv "$final_path/$location/conf.json.persistent" "/etc/ssowat/conf.json.persistent"
ynh_script_progression --message="Copying source files..." --time --weight=3

mv "/etc/update-motd.d/10-uname" "/etc/update-motd.d/10-uname.old"
mv "$final_path/10-uname" "/etc/update-motd.d/10-uname"
ynh_script_progression --message="Copying source files..." --time --weight=3

mv "/etc/issue" "/etc/issue.old"
mv "/etc/motd" "/etc/motd.old"
mv "$final_path/issue" "/etc/issue"
mv "$final_path/motd" "/etc/motd"
ynh_script_progression --message="Copying source files..." --time --weight=8

#=================================================
# GENERIC FINALIZATION
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

### For security reason, any app should set the permissions to root: before anything else.
### Then, if write authorization is needed, any access should be given only to directories
### that really need such authorization.

# Set permissions to app files
chown -R root: $final_path

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --time --last
