#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --time --weight=10

app=$YNH_APP_INSTANCE_NAME

final_path=$(ynh_app_setting_get --app=$app --key=final_path)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE APP MAIN DIR
#=================================================
ynh_script_progression --message="Removing app main directory..." --time --weight=30

# Remove the app directory securely
ynh_secure_remove --file="$final_path"

#=================================================
# COPY ITEMS BACK
#=================================================

ynh_secure_remove --file="/usr/share/ssowat/portal/assets/themes/moth/"
ynh_script_progression --message="Erasing source files..." --time --weight=15


rm "/etc/ssowat/conf.json.persistent"
mv "/etc/ssowat/conf.json.persistent.old" "/etc/ssowat/conf.json.persistent"
ynh_script_progression --message="Erasing source files..." --time --weight=3

rm "/etc/update-motd.d/10-uname"
mv "/etc/update-motd.d/10-uname.old" "/etc/update-motd.d/10-uname"

ynh_script_progression --message="Erasing source files..." --time --weight=3

rm "/etc/issue"
mv "/etc/issue.old" "/etc/issue"

ynh_script_progression --message="Erasing source files..." --time --weight=8

rm "/etc/motd"
mv "/etc/motd.old" "/etc/motd"

ynh_script_progression --message="Erasing source files..." --time --weight=8



#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --time --last
